version: '1.0'
name: pipeline-20250509
displayName: pipeline-20250509
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: build
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '10.3'
        commands:
          - apt-get update && apt-get install -y build-essential git wget pkg-config
          - apt-get install -y libssl-dev libcurl4-openssl-dev libc-ares-dev tcl tcl-dev libpugixml-dev sqlite3 libsqlite3-dev libboost-all-dev
          - git submodule update --init
          - mkdir build && cd build && cmake . -DCMAKE_BUILD_TYPE=Release. && make -j
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
