version: '1.0'
name: pipeline-20250509
displayName: pipeline-20250509
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: build
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: '9.4'
        commands:
          - sudo apt-get update && sudo apt-get install -y build-essential git wget pkg-config
          - sudo apt-get install -y libssl-dev libcurl4-openssl-dev libc-ares-dev tcl tcl-dev libpugixml-dev sqlite3 libsqlite3-dev
          - sudo git submodule update --init
          - sudo apt-get install -y libboost-all-dev
          - sudo mkdir opensource
          - cd opensource && sudo git clone https://github.com/libcpr/cpr.git && cd cpr && sudo mkdir build && cd build && sudo cmake .. -DCPR_USE_SYSTEM_CURL=ON && sudo make && sudo make install 
          - cd opensource && sudo wget https://ftp.gnu.org/gnu/osip/libosip2-5.3.1.tar.gz && sudo tar -zxvf libosip2-5.3.1.tar.gz && cd libosip2-5.3.1 && sudo ./configure && sudo make && sudo make install 
          - cd opensource && sudo wget http://download.savannah.nongnu.org/releases/exosip/libexosip2-5.3.0.tar.gz && sudo tar -zxvf libexosip2-5.3.0.tar.gz && cd libexosip2-5.3.0 && sudo ./configure && sudo make CFLAGS="-DENABLE_MAIN_SOCKET=1" && sudo make install 
          - sudo cp libexosip2.pc /usr/local/lib/pkgconfig/libexosip2.pc

          - '# 新建build目录，切换到build目录'
          - 'mkdir build && cd build '
          - '# 生成Unix平台的makefiles文件并执行构建'
          - cmake -G 'Unix Makefiles' ../ && make -j
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./bin
        caches: []
        notify: []
        strategy:
          retry: '0'
